const router = require("express").Router(); // Required to set new table
const {
  setTokenCookie,
  restoreUser,
  requireAuth,
} = require("../../utils/auth.js");
const { Sequelize } = require("sequelize");
const {
  Spot,
  Review,
  SpotImage,
  ReviewImage,
  User,
  Booking,
} = require("../../db/models");
const { Op } = require("sequelize");
/////////////////POST///////////////////
//Create review based on SpotId, need logIn
router.post("/:spotId/reviews", requireAuth, async (req, res, next) => {
  const { user } = req;
  const spotId = req.params.spotId;
  const { review, stars } = req.body;
  const spot = await Spot.findByPk(spotId);
  if (!spot) {
    return res.status(404).json({
      message: "Spot couldn't be found",
    });
  }
  const errors = {};

  if (!review || typeof review !== "string") {
    errors.review = "Review text is required";
  }

  if (!stars || typeof stars !== "number" || stars < 1 || stars > 5) {
    errors.stars = "Stars must be a number from 1 to 5";
  }

  if (Object.keys(errors).length > 0) {
    return res.status(400).json({
      message: "Bad Request",
      errors,
    });
  }
  const existingReview = await Review.findOne({
    where: {
      userId: user.id,
      spotId: spotId,
    },
  });

  if (existingReview) {
    return res.status(500).json({
      message: "User already has a review for this spot",
    });
  }
  const newReview = await Review.create({
    review,
    stars,
    userId: user.id,
    spotId: spotId,
  });
  res.status(201).json(newReview);
});

//Make a booking for a Spot based on SpotId

router.post("/:spotId/bookings", requireAuth, async (req, res, next) => {
  const { user } = req;
  const { spotId } = req.params;
  const { startDate, endDate } = req.body;

  try {
    const spot = await Spot.findByPk(spotId);

    if (!spot) {
      return res.status(404).json({
        message: "Spot couldn't be found",
      });
    }

    if (spot.ownerId === user.id) {
      return res.status(403).json({
        message: "Forbidden: You cannot book your own spot",
      });
    }

    const now = new Date();
    const start = new Date(startDate);
    const end = new Date(endDate);

    if (start < now) {
      return res.status(400).json({
        message: "Validation error",
        errors: {
          startDate: "startDate cannot be in the past",
        },
      });
    }

    if (end <= start) {
      return res.status(400).json({
        message: "Validation error",
        errors: {
          endDate: "endDate cannot be on or before startDate",
        },
      });
    }

    // Check for booking conflicts
    const conflictingBookings = await Booking.findAll({
      where: {
        spotId,
        [Op.or]: [
          {
            startDate: {
              [Op.in]: [start, end],
            },
          },
          {
            endDate: {
              [Op.in]: [start, end],
            },
          },
          {
            startDate: {
              [Op.between]: [start, end],
            },
          },
          {
            endDate: {
              [Op.between]: [start, end],
            },
          },
          {
            [Op.and]: [
              {
                startDate: {
                  [Op.lte]: start,
                },
              },
              {
                endDate: {
                  [Op.gte]: end,
                },
              },
            ],
          },
          {
            endDate: {
              [Op.eq]: start,
            },
          },
        ],
      },
    });

    if (conflictingBookings.length > 0) {
      return res.status(403).json({
        message: "Sorry, this spot is already booked for the specified dates",
        errors: {
          startDate: "Start date conflicts with an existing booking",
          endDate: "End date conflicts with an existing booking",
        },
      });
    }

    const newBooking = await Booking.create({
      spotId,
      userId: user.id,
      startDate: start.toISOString(),
      endDate: end.toISOString(),
    });

    res.status(201).json(newBooking);
  } catch (error) {
    next(error);
  }
});
//make new spot
router.post("/", requireAuth, async (req, res, next) => {
  const { user } = req;
  const { address, city, state, country, lat, lng, name, description, price } =
    req.body;
  if (
    !address ||
    !city ||
    !state ||
    !country ||
    !lat ||
    !lng ||
    !name ||
    !description ||
    !price
  ) {
    return res.status(400).json({
      message: "Bad Request", // (or "Validation error" if generated by Sequelize),
      errors: {
        address: "Street address is required",
        city: "City is required",
        state: "State is required",
        country: "Country is required",
        lat: "Latitude must be within -90 and 90",
        lng: "Longitude must be within -180 and 180",
        name: "Name must be less than 50 characters",
        description: "Description is required",
        price: "Price per day must be a positive number",
      },
    });
  }
  try {
    const newSpot = await Spot.create({
      ownerId: user.id,
      address,
      city,
      state,
      country,
      lat,
      lng,
      name,
      description,
      price,
    });
    res.status(201).json(newSpot);
  } catch (err) {
    next(err);
  }
});
//add imageto spot that belongs to the user
router.post("/:spotId/images", requireAuth, async (req, res, next) => {
  const { user } = req;
  const { spotId } = req.params;
  const { url, preview } = req.body;

  try {
    const spot = await Spot.findByPk(spotId);

    if (!spot) {
      return res.status(404).json({ message: "Spot couldn't be found" });
    }

    if (spot.ownerId !== user.id) {
      return res.status(403).json({ message: "Forbidden" });
    }

    const newImage = await SpotImage.create({
      spotId,
      url,
      preview,
    });

    res.status(200).json(newImage);
  } catch (err) {
    res.status(400);
    next(err);
  }
});

////////////GET//////////////

// router.use(requireAuth); // Everything Below this line need Auth in middleware

//Get All Bookings for Spot based on Spot Id
router.get("/:spotId/bookings", requireAuth, async (req, res, next) => {
  try {
    const { user } = req;
    const spotId = req.params.spotId;

    // Find the spot by ID
    const spot = await Spot.findByPk(spotId);
    if (!spot) {
      return res.status(404).json({
        message: "Spot couldn't be found",
      });
    }

    if (user.id !== spot.ownerId) {
      // Fetch bookings for non-owner users
      const userBookings = await Booking.findAll({
        where: { spotId },
        attributes: ["spotId", "startDate", "endDate"],
      });
      return res.status(200).json({ Bookings: userBookings });
    } else {
      // Fetch bookings for owner
      const ownerBookings = await Booking.findAll({
        where: { spotId },
        include: [{ model: User, attributes: ["id", "firstName", "lastName"] }],
      });
      return res.status(200).json({ Bookings: ownerBookings });
    }
  } catch (error) {
    console.error(error);
    next(error);
  }
});

//Get Reviews by SpotId//
router.get("/:spotId/reviews", async (req, res, next) => {
  const spotId = req.params.spotId;
  const spot = await Spot.findByPk(spotId); //finding Obj by SpotId
  if (!spot) {
    return res.status(404).json({
      message: "Spot couldn't be found",
    });
  }
  const Reviews = await spot.getReviews({
    include: [
      { model: User, attributes: ["id", "firstName", "lastName"] },
      {
        model: ReviewImage,
        attributes: { exclude: ["reviewId", "createdAt", "updatedAt"] },
      },
    ],
  });

  res.json(Reviews);
});

//get spot owned by current user
router.get("/current", requireAuth, async (req, res) => {
  const { user } = req;
  const spots = await user.getSpots({
    attributes: {
      include: [
        [Sequelize.fn("AVG", Sequelize.col("Reviews.stars")), "avgRating"],
      ],
    },
    include: [
      {
        model: Review,
        attributes: [],
      },
      {
        model: SpotImage,
        attributes: ["url"],
        where: { preview: true },
        required: false,
        as: "previewImage",
      },
    ],
    group: ["Spot.id", "previewImage.id"],
  });
  res.json(spots);
});

//get spot by spotId
router.get("/:spotId", async (req, res, next) => {
  const spotId = req.params.spotId;
  const data = await Spot.findByPk(spotId, {
    attributes: {
      include: [
        [Sequelize.fn("COUNT", Sequelize.col("Reviews.id")), "numReviews"],
        [Sequelize.fn("AVG", Sequelize.col("Reviews.stars")), "avgStarRating"],
      ],
    },
    include: [
      {
        model: Review,
        attributes: [],
      },
    ],
  });
  if (!data.id) {
    return res.status(404).json({ message: "Spot couldn't be found" });
  }

  const SpotImages = await SpotImage.findAll({
    where: { spotId: spotId },
    attributes: ["id", "url", "preview"],
    order: [["id", "ASC"]],
  });
  const Owner = await data.getUser({
    attributes: ["id", "firstName", "lastName"],
  });
  res.json({ ...data.toJSON(), SpotImages, Owner });
});

//GET ALL SPOTS//
router.get("/", async (req, res, next) => {
  const Spots = await Spot.findAll({
    attributes: {
      include: [
        [Sequelize.fn("AVG", Sequelize.col("Reviews.stars")), "avgRating"],
      ],
    },
    include: [
      {
        model: Review,
        attributes: [],
      },
      {
        model: SpotImage,
        attributes: ["url"],
        where: { preview: true },
        required: false,
        as: "previewImage",
      },
    ],
    group: ["Spot.id", "previewImage.id"],
  });
  res.json({ Spots });
});

/////////////////////PUT//////////////////////
//Edit a Spot//
router.put("/:spotId", requireAuth, async (req, res, next) => {
  const { user } = req;
  const { spotId } = req.params;
  const { address, city, state, country, lat, lng, name, description, price } =
    req.body;
  const UpdatedSpot = await Spot.findByPk(spotId); //find the spot with its ownerId in it
  try {
    if (!UpdatedSpot) {
      return res.status(404).json({ message: "Spot couldn't be found" });
    }
    if (UpdatedSpot.ownerId !== user.id) {
      //compare ownerId
      return res.status(403).json({ message: "Forbidden" });
    }
    if (
      !address ||
      !city ||
      !state ||
      !country ||
      !lat ||
      !lng ||
      !name ||
      !description ||
      !price
    ) {
      return res.status(400).json({
        message: "Bad Request", // (or "Validation error" if generated by Sequelize),
        errors: {
          address: "Street address is required",
          city: "City is required",
          state: "State is required",
          country: "Country is required",
          lat: "Latitude must be within -90 and 90",
          lng: "Longitude must be within -180 and 180",
          name: "Name must be less than 50 characters",
          description: "Description is required",
          price: "Price per day must be a positive number",
        },
      });
    }
    // Update the spot with new data
    const updatedData = await UpdatedSpot.update({
      ...req.body,
      updatedAt: new Date(),
    });

    res.status(200).json(updatedData);
  } catch (err) {
    next(err);
  }
});

////////////////DELETE/////////////////
router.delete("/:spotId", requireAuth, async (req, res, next) => {
  const { user } = req;
  const spotId = req.params.spotId;
  try {
    const spot = await Spot.findByPk(spotId); //SpotId Obj with OwnerId
    if (!spot) {
      return res.status(404).json({ message: "Spot couldn't be found" });
    }
    if (spot.ownerId !== user.id) {
      return res.status(403).json({ message: "Forbidden" });
    }
    await spot.destroy();
    res.status(200).json({
      message: "Successfully deleted",
    });
  } catch (error) {
    next(error);
  }
});

module.exports = router; // Required to set new table
